### ISSUE TITLE
Migration routine incompatible with current Stripe API?

### ISSUE THREAD

**Issue by ppmathis** [blesta/gateway-stripepayments#18]
The current version of the module available in this repository [checks](https://github.com/blesta/gateway-stripepayments/blob/master/stripe_payments.php#L168-L176) if the Stripe customer object has any active card associated using this condition:

```php
if (isset($customer->active_card->id)) {
```

On our system this condition does not match a single customer using Stripe payments, as the field `active_card` on `Stripe\Customer` has been deprecated for ages back with API 2013-07-05 and replaced with `cards` and `default_card`: https://stripe.com/docs/upgrades#2013-07-05

Which then once again got changed to `sources` and `default_source` with API 2015-02-18: https://stripe.com/docs/upgrades#2015-02-18

Is it possible that this migration routine has been developed against a really old Stripe API version, as Stripe requires manually triggering an upgrade of the API version inside the customer account? In my case the following changes to `stripe_payments.php` have allowed the migration routine to gather the new payment source identifiers using API 2019-09-09:

```php
168c168
<                 if (isset($customer->active_card->id)) {
---
>                 if (isset($customer->default_source)) {
172c172
<                         'reference_id' => $customer->active_card->id,
---
>                         'reference_id' => $customer->default_source,
```

**Comment by JReissmueller** [comment]
Thanks for the feedback! Yea this was developed using a sandbox account we have so it is quite possible that the same consistency with new API version was not enforced.  Would you be willing to create a bug post as well on the forums with your proposed solutions.  Others may find it helpful. https://www.blesta.com/forums/index.php?/forum/22-bugs/
